url: https://eevol.github.io
baseurl: ""

# Site settings
title: eevol
email: ping@eevol.lu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 53c6b8
  secondary: 206058
  secondary-dark: 206058

exclude:
- node_modules
- Gemfile
- npm-debug.log
- gulpfile.js
- package.json
- README.md
- .gitignore

#Portfolio
collections:
- projects

# Team names, titles and social links
people:
- name: Thierry Nicola
  pic: thierry
  position: Frontend & Server Developer
  email: thierry@eevol.lu
  social:
    - title: twitter
      url: http://twitter.com/littleiffel
    - title: github
      url: http://github.com/littleiffel


- name: Jakob Drangmeister
  pic: jakob
  position: iOS & Web Developer
  email: jakob@eevol.lu
  social:
    - title: twitter
      url: http://twitter.com/issue2k
    - title: github
      url: http://github.com/issue2k


- name: Andreas Weber
  pic: andreas
  position: Android & Web Developer
  email: andreas@eevol.lu
  social:
    - title: github
      url: http://github.com/anti43


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/eevol_lu
  - title: github
    url: http://github.com/eevol

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

