url: http://eevol.lu
baseurl: ""

# Site settings
title: eevol
email: ping@eevol.lu
description: "eevol provides full services for your mobile- & web-apps. During every step of the development the team aims for stability while maintaining flexibility for the customer. eevol helps you to get started and brings your idea to the App Stores directly to the people."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 53c6b8
  secondary: 206058
  secondary-dark: 206058

exclude:
- node_modules
- Gemfile
- npm-debug.log
- gulpfile.js
- package.json
- README.md
- .gitignore

#Portfolio
collections:
  projects:
    output: true
  jobs:
    output: true

# Team names, titles and social links
people:
- name: Thierry Nicola
  pic: thierry
  position: CEO / Frontend / Server Developer
  email: thierry@eevol.lu
  social:
    - title: twitter
      url: http://twitter.com/littleiffel
    - title: github
      url: http://github.com/littleiffel


- name: Jakob Drangmeister
  pic: jakob
  position: iOS / Web Developer
  email: jakob@eevol.lu
  social:
    - title: twitter
      url: http://twitter.com/issue2k
    - title: github
      url: http://github.com/issue2k


- name: Andreas Weber
  pic: andreas
  position: Android / Web Developer
  email: andreas@eevol.lu
  social:
    - title: github
      url: http://github.com/anti43


- name: Tomas Kamarauskas
  pic: tomas
  position: UX / iOS Developer
  email: tomas@eevol.lu
  social:
    - title: github
      url: https://github.com/tomasKa
    - title: twitter
      url: https://twitter.com/KaMatom  


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/eevol_lu
  - title: github
    url: http://github.com/eevol

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

